name: home
timestamp: 1480624821
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home
  timestamp: 1472319055
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  resume: Resume
  portfolio: Portfolio
  utility: Utility
  expanded: Expanded
  above: Above
  testimonials: Testimonials
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9608: 'Logo / Image'
  menu:
    menu-6409: Menu
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
    owlcarousel-7166: 'Owl Carousel'
  infocard:
    infocard-6612: 'Intro Cards'
    infocard-4698: 'Intro Cards'
    infocard-5797: 'Intro Cards'
  sectiontitle:
    sectiontitle-7684: 'Section Title'
    sectiontitle-6211: 'Recent Readings'
    sectiontitle-3112: 'My Experience'
    sectiontitle-8813: 'MY Education'
    sectiontitle-2967: 'Section Title'
    sectiontitle-4237: 'Section Title'
  profile:
    profile-6209: 'My Profile'
  skills:
    skills-8030: Skills
  bio:
    bio-4636: 'Mini Bio'
  cv:
    cv-9087: Resume
  spacer:
    spacer-spacer-6646: Spacer
    spacer-spacer-5194: Spacer
  portfolio:
    portfolio-6995: Projects
  process:
    process-3920: Process
  quote:
    quote-4332: Quote
  timeline:
    timeline-4855: Timeline
  selfie-circle-widget:
    selfie-circle-widget-9207: 'Circle Widget'
    selfie-circle-widget-1947: 'Circle Widget'
    selfie-circle-widget-7655: 'Circle Widget'
    selfie-circle-widget-2478: 'Circle Widget'
  googlemap:
    googlemap-4972: 'Google Map'
  custom:
    custom-5682: 'Contact SC'
  totop:
    totop-8670: 'To Top'
  email:
    email-1270: Email
  copyright:
    copyright-1736: Copyright
  phone:
    phone-9918: Phone
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
