version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home
  timestamp: 1472319055
layout:
  /navigation/:
    -
      - 'logo-9608 25'
      - 'menu-6409 75'
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 'infocard-6612 33.3'
      - 'infocard-4698 33.3'
      - 'infocard-5797 33.3'
  /features/:
    -
      - sectiontitle-7684
    -
      - 'profile-6209 25'
      - 'skills-8030 25'
      - 'bio-4636 50'
  /resume/:
    -
      - cv-9087
  /protfolio/:
    -
      - sectiontitle-6211
    -
      - portfolio-6995
  /utility/:
    -
      - sectiontitle-3112
    -
      - process-3920
  /above/:
    -
      - sectiontitle-8813
    -
      - timeline-4855
  /testimonials/:
    -
      - sectiontitle-2967
    -
      - owlcarousel-7166
  /expanded/:
    -
      - custom-8324
  /container-main/:
    -
      -
        'mainbar 90':
          -
            - sectiontitle-4237
          -
            - 'selfie-circle-widget-9207 25'
            - 'selfie-circle-widget-1947 25'
            - 'selfie-circle-widget-7655 25'
            - 'selfie-circle-widget-2478 25'
          -
            - custom-5682
      -
        'sidebar 10': {  }
  /footer/:
    -
      - totop-8670
    -
      - 'custom-1125 25'
      - 'copyright-1736 50'
      - 'custom-9450 25'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  resume:
    type: section
    attributes:
      boxed: ''
  protfolio:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      link: '1'
      text: 'John Doe'
      class: ''
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      full: '1'
      items:
        -
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/09/selfie-slider-two.jpg'
          title: 'Selfie is here!'
          desc: 'Begin your journey with a brand new &raquo;free&laquo; Gantry 5 template from RocketTheme.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonclass: ''
          name: 'Item 1'
        -
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/09/selfie-slider-two.jpg'
          title: 'Selfie is Gantry powered!'
          desc: 'Selfie is based on the powerful Gantry framework.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonclass: ''
          name: 'Item 2'
  infocard-6612:
    title: 'Intro Cards'
    attributes:
      title: 'SEO OPTIMIZATION'
      desc: 'Lorem ipsum dolor sit amet, consectetur uos adipisicing elit Expedita voluptatu necessitatibus deleniti nisi.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_notice.png'
    block:
      class: border-left
      variations: center
  infocard-4698:
    title: 'Intro Cards'
    attributes:
      title: 'CREATIVE DESIGNER'
      desc: 'Lorem ipsum dolor sit amet, consectetur uos adipisicing elit Expedita voluptatu necessitatibus deleniti nisi.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_bulb.png'
    block:
      class: 'border-left border-right'
      variations: center
  infocard-5797:
    title: 'Intro Cards'
    attributes:
      title: '2015 DESIGN AWARD'
      desc: 'Lorem ipsum dolor sit amet, consectetur uos adipisicing elit Expedita voluptatu necessitatibus deleniti nisi.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_award.png'
    block:
      class: border-right
      variations: center
  sectiontitle-7684:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-heart-o fa-2x'
      title: 'KNOW ABOUT ME'
      label: 'Myself & More'
    block:
      variations: center
  profile-6209:
    title: 'My Profile'
    attributes:
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/11/selfe-profile-new-one.jpg'
      name: 'John Doe Smith'
      title: 'Designer / Photographer'
      desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore duis aute irure dolor in reprehende in voluptate velit esse.\n\n"
      dob: '1980-04-25'
      phone: '+61 854 895 57 Ext. 123'
      email: john@johndoesmith.com
      address: '224 rosemount ave'
      social:
        -
          icon: 'fa fa-facebook-square'
          text: ''
          link: ''
          name: 'New item'
        -
          icon: 'fa fa-twitter-square'
          text: ''
          link: ''
          name: 'New item'
        -
          icon: 'fa fa-google-plus-circle'
          text: ''
          link: ''
          name: 'New item'
    block:
      class: 'nomarginleft nomarginright'
  skills-8030:
    attributes:
      stats:
        -
          icon: 'fa fa-apple fa-2x'
          label: 'Frequent Update'
          value: '627'
          name: 'New item'
        -
          icon: 'fa fa-apple fa-2x'
          label: 'Sleeping Hours'
          value: '627'
          name: 'New item'
        -
          icon: 'fa fa-apple fa-2x'
          label: 'Lines of Code'
          value: '627'
          name: 'New item'
        -
          icon: 'fa fa-apple fa-2x'
          label: 'Happy Customers'
          value: '627'
          name: 'New item'
      skills:
        -
          title: PHP
          percent: '75'
          name: PHP
        -
          title: 'Html / css'
          percent: '80'
          name: Html
        -
          title: WordPress
          percent: '95'
          name: WP
        -
          title: photoshop
          percent: '65'
          name: PS
        -
          title: photoshop
          percent: '56'
          name: PS2
        -
          title: photoshop
          percent: '90'
          name: 'PS#'
    block:
      class: 'nomarginleft nomarginright'
  bio-4636:
    title: 'Mini Bio'
    attributes:
      name: 'John Smith'
      subtitle: 'Creative and Professional Designer who loves everything around web design & programming.'
      text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nunc lectus, vehicula at orci vel, suscipit finibus massa. Aenean porttitor nunc vel justo fringilla, eget tempor nibh semper. Ut eget ultricies elit, tincidunt varius mauris. Duis nisl magna, placerat sit amet felis eget, aliquam facilisis urna. In aliquet ornare velit sit amet mollis. Donec molestie sagittis urna, ac tincidunt mauris placerat non. Nulla libero felis, bibendum sed ultricies sed, accumsan sit amet felis.\n</p><p>\nPellentesque tincidunt condimentum neque. Fusce faucibus, lorem eget interdum gravida, urna odio sodales nisi, et aliquam odio purus eget purus. Ut tristique, nunc id elementum rhoncus, risus.</p>"
      signature: DBahl
  cv-9087:
    title: Resume
    attributes:
      class: accent
      label: 'I am ready for any Project,'
      title: 'Contact Me?'
      linktxt: 'Hire Me'
      link: '#contact'
      linktxt2: 'Download CV'
      icon: 'fa fa-arrow-down'
      location: 'gantry-media://Mikhail_Johnson_Resume2016[203].pdf'
    block:
      variations: center
  sectiontitle-6211:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-coffee fa-2x'
      title: 'LATEST PROJECTS'
      label: 'Pride & Joy'
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut lobortis nulla luctus et ultrices posuere cubilia,\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae"
    block:
      variations: center
  portfolio-6995:
    title: Projects
  sectiontitle-3112:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-wrench fa-2x'
      title: 'MY PROCESS'
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut lobortis nulla luctus et ultrices posuere cubilia,\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae"
    block:
      variations: center
  process-3920:
    attributes:
      items:
        -
          title: Planning
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: Designing
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: Implementing
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: Production
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
  sectiontitle-8813:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-trophy fa-2x'
      title: 'MY EXPERIENCE'
      label: 'Wide & Powerful'
    block:
      variations: center
  timeline-4855:
    attributes:
      sections:
        -
          title: Education
          icon: 'fa fa-briefcase'
          name: Education
      items:
        -
          section: Education
          icon: 'fa fa-compass'
          title: 'Lion Trade Corporation1'
          link: /
          label: 'Project Manager'
          desc: 'Lorem ipsum dolor sit amet, consectetur adicing adipisicing elit Expedita voluptatum deleniti eni necessitatibus deleniti nisi Lorem.'
          info1: 'Recent Training''s:'
          info1_sub: 'Recent Training''s:'
          info2: 'Recent Training''s:'
          info2_sub: 'PMP, ITIL & CCNA'
          date: '1051'
          name: 'New item'
        -
          section: Education
          icon: 'fa fa-compass3'
          title: 'Lion Trade Corporation'
          link: /
          label: 'Sleeping Hours'
          desc: 'Lorem ipsum dolor sit amet, consectetur adicing adipisicing elit Expedita voluptatum deleniti eni necessitatibus deleniti nisi Lorem.'
          info1: 'Recent Training''s:'
          info1_sub: 'Recent Training''s:'
          info2: 'Recent Training''s:'
          info2_sub: 'Recent Training''s:'
          date: '2016'
          name: 'New item'
        -
          section: Education
          icon: 'fa fa-compass'
          title: 'Lion Trade Corporation2'
          link: /
          label: 'Awards & Accolades'
          desc: 'Lorem ipsum dolor sit amet, consectetur adicing adipisicing elit Expedita voluptatum deleniti eni necessitatibus deleniti nisi Lorem.'
          info1: 'Recent Training''s:'
          info1_sub: 'Recent Training''s:'
          info2: 'Recent Training''s:'
          info2_sub: 'Recent Training''s:'
          date: '2019'
          name: 'New item'
  sectiontitle-2967:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-bullhorn fa-2x'
      title: 'My References'
    block:
      variations: center
  owlcarousel-7166:
    title: 'Owl Carousel'
    attributes:
      variant: o3
      nav: disable
      dots: enable
      autoplay: enable
      items:
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - John Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - Jack Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - Jane Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
    block:
      class: 'nomargintop nopaddingtop'
  custom-8324:
    title: Quote
    attributes:
      html: ''
  sectiontitle-4237:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-compress fa-2x'
      title: 'STAY IN TOUCH'
      label: 'Available & Always'
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut lobortis nulla luctus et ultrices posuere cubilia,\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae"
    block:
      variations: center
  selfie-circle-widget-9207:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-phone'
      label: '+1 323-444-4553'
      desc: 'REACH ME ANYTIME'
  selfie-circle-widget-1947:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-paperclip fa-2x'
      label: example@site.com
      desc: 'MY PERSONAL EMAIL'
  selfie-circle-widget-7655:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-twitter'
      label: '@johnsmith'
      desc: 'SEND TWEET'
  selfie-circle-widget-2478:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-envelope'
      label: www.johnsmith.com
      desc: 'PROFESSIONAL WEBSITE'
  custom-5682:
    title: 'Custom HTML'
    attributes:
      html: '[contact-form-7 id="12" title="Contact form 1"]'
      filter: '1'
  totop-8670:
    title: 'To Top'
    attributes:
      icon: 'fa fa-chevron-up fa-fw'
      content: ''
  custom-1125:
    title: 'Custom HTML'
    attributes:
      html: '<a href="mailto:example@site.com">example@site.com</a>'
    block:
      class: selfie-footer-email
  copyright-1736:
    attributes:
      date:
        start: '2016'
        end: now
      owner: ProfTeam
      link: 'http://www.profteamsolutions.com'
      target: _blank
      additional:
        text: 'All Rights Reserved.'
  custom-9450:
    title: 'Custom HTML'
    attributes:
      html: '<a href="tel:+1323-444-4553">+1323-444-4553</a>'
    block:
      class: selfie-footer-phone
