version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home
  timestamp: 1472319055
layout:
  /navigation/:
    -
      - 'logo-9608 25'
      - 'menu-6409 75'
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 'infocard-6612 33.3'
      - 'infocard-4698 33.3'
      - 'infocard-5797 33.3'
  /features/:
    -
      - sectiontitle-7684
    -
      - 'profile-6209 25'
      - 'skills-8030 25'
      - 'bio-4636 50'
  /resume/:
    -
      - cv-9087
  /portfolio/:
    -
      - sectiontitle-6211
    -
      - 'spacer-6646 10'
      - 'portfolio-6995 80'
      - 'spacer-5194 10'
  /utility/:
    -
      - sectiontitle-3112
    -
      - process-3920
  /expanded/:
    -
      - quote-4332
  /above/:
    -
      - sectiontitle-8813
    -
      - timeline-4855
  /testimonials/:
    -
      - sectiontitle-2967
    -
      - owlcarousel-7166
  /container-main/:
    -
      -
        'mainbar 90':
          -
            - sectiontitle-4237
          -
            - googlemap-4972
          -
            - custom-5682
      -
        'sidebar 10': {  }
  /footer/:
    -
      - totop-8670
    -
      - 'email-1270 25'
      - 'copyright-1736 50'
      - 'phone-9918 25'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  resume:
    type: section
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      image: ''
      link: '1'
      text: 'Prachi Sharma'
      class: g-logo
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: disable
      dots: disable
      slides: '1'
      autoplay: disable
      full: '1'
      loop: '0'
      items:
        -
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/09/selfie-slider-two.jpg'
          title: 'I Am Prachi Sharma'
          desc: 'I am an Certified Clinical Research Associate in the great city of Toronto.'
          link: ''
          linktext: ''
          buttonclass: ''
          name: 'Item 1'
  infocard-6612:
    title: 'Intro Cards'
    attributes:
      title: Personality
      desc: 'Gain insight into my personality through a combination of characteristics and qualities.'
      display: img
      icon: 'fa fa-lightbulb-o'
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_notice.png'
    block:
      class: border-left
      variations: center
      extra:
        -
          style: 'padding: 50px 15px;'
  infocard-4698:
    title: 'Intro Cards'
    attributes:
      title: Mindset
      desc: 'Understand my mindset by discovering my way of thinking and set of attitudes and skills.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_bulb.png'
    block:
      class: 'border-left border-right'
      variations: center
      extra:
        -
          style: 'padding: 50px 15px;'
  infocard-5797:
    title: 'Intro Cards'
    attributes:
      title: Character
      desc: 'Take a look at the attributes and features that make up my distinguished individuality. '
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_award.png'
    block:
      class: border-right
      variations: center
      extra:
        -
          style: 'padding: 50px 15px;'
  sectiontitle-7684:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-heart-o fa-2x'
      title: 'KNOW ABOUT ME'
      label: 'Myself & More'
    block:
      variations: center
  profile-6209:
    title: 'My Profile'
    attributes:
      image: 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/4/005/053/23e/2fbd43d.jpg'
      name: 'Prachi Sharma'
      title: 'Certified Clinical Research Associate'
      desc: "276-001  Clinical Trial Research Coordinator\n276-002  Research Ethics and Regulatory Affairs\n276-003  Clinical Trial Methodologies in Practice\n\n\n"
      dob: '1983-05-29'
      phone: 905-802-3694
      email: prachisharma.cra@outlook.com
      address: ''
      social:
        -
          icon: 'fa fa-linkedin-square fa-2x'
          text: ''
          link: 'https://ca.linkedin.com/in/prachi-sharma-63325659'
          name: linkedin
        -
          icon: 'fa fa-facebook-square fa-2x'
          text: ''
          link: //www.facebook.com
          name: facebook
        -
          icon: 'fa fa-twitter-square fa-2x'
          text: ''
          link: //www.twitter.com
          name: twitter
        -
          icon: 'fa fa-google-plus-circle fa-2x'
          text: ''
          link: 'https://plus.google.com/'
          name: google
        -
          icon: 'fa fa-pinterest-square fa-2x'
          text: ''
          link: 'https://www.pinterest.com/'
          name: pinterest
        -
          icon: 'fa fa-youtube-play fa-2x'
          text: ''
          link: //www.youtube.com
          name: youtube
    block:
      class: 'nomarginleft nomarginright'
  skills-8030:
    attributes:
      stats:
        -
          icon: 'fa fa-flag fa-2x'
          label: 'Years Experience'
          value: '8'
          name: Experience
        -
          icon: 'fa fa-thumbs-up fa-2x'
          label: 'Volunteer Efforts'
          value: '2'
          name: Volunteer
        -
          icon: 'fa fa-comments fa-2x'
          label: Languages
          value: '2'
          name: Languages
        -
          icon: 'fa fa-trophy fa-2x'
          label: Awards
          value: '10'
          name: Awards
      skills:
        -
          title: Leadership
          percent: '70'
          name: LeaderShip
        -
          title: Initiative
          percent: '75'
          name: Initiative
        -
          title: Communication
          percent: '92'
          name: Communication
        -
          title: Enthusiaim
          percent: '70'
          name: Enthusiaim
        -
          title: 'Team Work'
          percent: '83'
          name: 'Team Work'
        -
          title: Creativity
          percent: '86'
          name: Creativity
    block:
      class: 'nomarginleft nomarginright'
  bio-4636:
    title: 'Mini Bio'
    attributes:
      name: 'Prachi Sharma'
      subtitle: '“America''s health care system is neither healthy, caring, nor a system.” '
      text: "<p>Helped with designing and conducting clinical trial and reviewed protocol\nConducted study visits and collected informed consent and helped with subject recruitment \nAssisted Regulatory Affairs Manager in creation and collection of regulatory documents for different study sites\nExcellent knowledge of research ethics, legislative guidelines and regulatory issues\nEnsured compliance with appropriate Company SOPs GCP and ICH guidelines\nHelped clinical team in performing internal monitoring, site initiation visit, and close out visits\nAssisted with protocol writing, developing and managing source documents\nAttended investigator meetings and conferences and gave presentations on behalf of company\nTracked all time and expenses for clinical research team and submitted in a timely manner. Provided monthly metrics reports to the revenue department. Provided budget estimates for clinical studies\n </p>"
      signature: 'Prachi Sharma'
  cv-9087:
    title: Resume
    attributes:
      class: accent
      label: 'I am ready for any challenge,'
      title: 'Contact Me!'
      linktxt: 'Hire Me'
      link: '#g-container-main'
      linktxt2: 'Download CV'
      icon: 'fa fa-arrow-down'
      location: 'gantry-media://Prachi Sharma Resume.docx'
    block:
      variations: center
  sectiontitle-6211:
    title: 'Recent Readings'
    attributes:
      icon: 'fa fa-coffee fa-2x'
      title: 'Recent Readings'
      label: 'Pride & Joy'
      desc: 'Gain insight into my personality and character by viewing my recent readings from books and articles to blogs and publications.'
    block:
      variations: center
  portfolio-6995:
    title: Projects
    attributes:
      items:
        -
          image: 'gantry-media://savannah/H1.jpg'
          title: 'The Rave'
          label: 'Edgar Allen Poe'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/h3.jpg'
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/h2.jpg'
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
  sectiontitle-3112:
    title: 'My Experience'
    attributes:
      icon: 'fa fa-wrench fa-2x'
      title: 'MY EXPERIENCE'
      label: 'Path to Success'
      desc: 'Showcasing relevant work experience is critical in highlighting an individual’s career path and progress.'
    block:
      variations: center
  process-3920:
    attributes:
      items:
        -
          title: 'KGK Synergize Inc.                     '
          desc: 'Clinical Research Associate/ Clinical Trial Coordinator'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: 'Tata International Limited'
          desc: 'Research Associate'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: 'Juravinski Cancer Hospital'
          desc: 'Clinical Research Assistant'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: 'Serum Institute of India Ltd'
          desc: 'Research Trainee'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
  quote-4332:
    attributes:
      text: '“Everyone should have health insurance? I say everyone should have health care. I''m not selling insurance.” '
  sectiontitle-8813:
    title: 'MY Education'
    attributes:
      icon: 'fa fa-trophy fa-2x'
      title: 'MY Education'
      label: 'Power of Learning'
    block:
      variations: center
  timeline-4855:
    attributes:
      sections:
        -
          title: latest
          icon: 'fa fa-graduation-cap'
          name: Education
      items:
        -
          section: latest
          icon: 'fa fa-compass'
          title: 'Mcmaster University'
          link: /
          label: 'Master of Science (Molecular Biology)'
          desc: 'Hamilton, Ontario'
          date: '1999 - 2003'
          name: 'New item'
        -
          section: latest
          icon: 'fa fa-compass'
          title: 'Vikram University'
          link: /
          label: 'Masters of Science (Biochemistry & Microbiology)                                  '
          desc: India
          date: 'July 1999 - Jun 2001'
          name: 'New item'
        -
          section: latest
          icon: 'fa fa-compass'
          title: 'D.A.V.V University'
          link: /
          label: 'Bachelor of Science (Biochemistry & Microbiology)                                '
          desc: India
          date: '2019'
          name: 'New item'
  sectiontitle-2967:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-bullhorn fa-2x'
      title: 'My Testimonials'
    block:
      variations: center
  owlcarousel-7166:
    title: 'Owl Carousel'
    attributes:
      variant: o3
      nav: disable
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      items:
        -
          image: ''
          title: ''
          desc: '"She is super good and nice and i like her." - John Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Loved working with her she is great at getting things done." - Jack Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Very quick and sharp and communicates good." - Jane Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
    block:
      class: 'nomargintop nopaddingtop'
  sectiontitle-4237:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-compress fa-2x'
      title: 'STAY IN TOUCH'
      label: 'Available & Always'
      desc: 'Feel free to reach out to me at anytime, I''m always happy to connect !'
    block:
      variations: center
  googlemap-4972:
    title: 'Google Map'
    attributes:
      apikey: AIzaSyBMkRoN_9gBXocQZ-FfBGwLEJayFq7dlXc
      width: 100%
      height: 300px
      maptype: ROADMAP
      latitude: '43.6278147'
      longitude: '-79.505008'
      zoom: '14'
      defaultmarker: show
      markertext: ''
      markerstate: '1'
      scrollwheel: '0'
      dragging: enabled
      snazzymaps: "[{\n    \"featureType\": \"landscape.natural\",\n    \"elementType\": \"geometry.fill\",\n    \"stylers\": [{\n        \"visibility\": \"on\"\n    }, {\n        \"color\": \"#e0efef\"\n    }]\n}, {\n    \"featureType\": \"poi\",\n    \"elementType\": \"geometry.fill\",\n    \"stylers\": [{\n        \"visibility\": \"on\"\n    }, {\n        \"hue\": \"#1900ff\"\n    }, {\n        \"color\": \"#c0e8e8\"\n    }]\n}, {\n    \"featureType\": \"road\",\n    \"elementType\": \"geometry\",\n    \"stylers\": [{\n        \"lightness\": 100\n    }, {\n        \"visibility\": \"simplified\"\n    }]\n}, {\n    \"featureType\": \"road\",\n    \"elementType\": \"labels\",\n    \"stylers\": [{\n        \"visibility\": \"off\"\n    }]\n}, {\n    \"featureType\": \"transit.line\",\n    \"elementType\": \"geometry\",\n    \"stylers\": [{\n        \"visibility\": \"on\"\n    }, {\n        \"lightness\": 700\n    }]\n}, {\n    \"featureType\": \"water\",\n    \"elementType\": \"all\",\n    \"stylers\": [{\n        \"color\": \"#7dcdcd\"\n    }]\n}]"
      css:
        class: map-canvas
  custom-5682:
    title: 'Contact SC'
    attributes:
      html: '[contact-form-7 id="811" title="Selfie Form"]'
      filter: '1'
  totop-8670:
    title: 'To Top'
    attributes:
      icon: 'fa fa-angle-up fa-fw fa-2x'
      content: ''
    block:
      class: g-flushed
  email-1270:
    attributes:
      email: prachisharma.cra@outlook.com
    block:
      class: 'item_left selfie-footer-email'
  copyright-1736:
    attributes:
      date:
        start: '2016'
        end: now
      owner: 'ProfTeam All Rights Reserved.'
      link: 'http://www.profteamsolutions.com'
      target: _blank
      additional:
        text: ''
    block:
      class: selfie-copyrights
  phone-9918:
    attributes:
      tel: 905-802-3694
    block:
      class: 'selfie-footer-phone item_right'
