version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home
  timestamp: 1472319055
layout:
  /navigation/:
    -
      - 'logo-9608 25'
      - 'menu-6409 75'
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 'infocard-6612 33.3'
      - 'infocard-4698 33.3'
      - 'infocard-5797 33.3'
  /features/:
    -
      - sectiontitle-7684
    -
      - 'profile-6209 25'
      - 'skills-8030 25'
      - 'bio-4636 50'
  /resume/:
    -
      - cv-9087
  /portfolio/:
    -
      - sectiontitle-6211
    -
      - 'spacer-spacer-6646 10'
      - 'portfolio-6995 80'
      - 'spacer-spacer-5194 10'
  /utility/:
    -
      - sectiontitle-3112
    -
      - process-3920
  /expanded/:
    -
      - quote-4332
  /above/:
    -
      - sectiontitle-8813
    -
      - timeline-4855
  /testimonials/:
    -
      - sectiontitle-2967
    -
      - owlcarousel-7166
  /container-main/:
    -
      -
        'mainbar 90':
          -
            - sectiontitle-4237
          -
            - 'selfie-circle-widget-9207 25'
            - 'selfie-circle-widget-1947 25'
            - 'selfie-circle-widget-7655 25'
            - 'selfie-circle-widget-2478 25'
          -
            - googlemap-4972
          -
            - custom-5682
      -
        'sidebar 10': {  }
  /footer/:
    -
      - totop-8670
    -
      - 'email-1270 25'
      - 'copyright-1736 50'
      - 'phone-9918 25'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  resume:
    type: section
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      image: ''
      link: '1'
      text: 'Dean Balh'
      class: g-logo
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: disable
      dots: disable
      slides: '1'
      autoplay: disable
      full: '1'
      loop: '0'
      items:
        -
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/09/selfie-slider-two.jpg'
          title: 'I Am Dean Balh'
          desc: "I am an Award Winning Sales Representative\nin the great city of toronto."
          link: ''
          linktext: ''
          buttonclass: ''
          name: 'Item 1'
  infocard-6612:
    title: 'Intro Cards'
    attributes:
      title: Personality
      desc: 'Gain insight into my personality through a combination of characteristics and qualities.'
      display: img
      icon: 'fa fa-lightbulb-o'
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_notice.png'
    block:
      class: border-left
      variations: center
      extra:
        -
          style: 'padding: 50px 15px;'
  infocard-4698:
    title: 'Intro Cards'
    attributes:
      title: Mindset
      desc: 'Understand my mindset by discovering my way of thinking and set of attitudes and skills.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_bulb.png'
    block:
      class: 'border-left border-right'
      variations: center
      extra:
        -
          style: 'padding: 50px 15px;'
  infocard-5797:
    title: 'Intro Cards'
    attributes:
      title: Character
      desc: 'Take a look at the attributes and features that make up my distinguished individuality. '
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_award.png'
    block:
      class: border-right
      variations: center
      extra:
        -
          style: 'padding: 50px 15px;'
  sectiontitle-7684:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-heart-o fa-2x'
      title: 'KNOW ABOUT ME'
      label: 'Myself & More'
    block:
      variations: center
  profile-6209:
    title: 'My Profile'
    attributes:
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/11/selfe-profile-new-one.jpg'
      name: 'John Doe Smith'
      title: 'Designer / Photographer'
      desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore duis aute irure dolor in reprehende in voluptate velit esse.\n\n"
      dob: '1980-04-25'
      phone: '+61 854 895 57 Ext. 123'
      email: john@johndoesmith.com
      address: '224 rosemount ave'
      social:
        -
          icon: 'fa fa-linkedin-square fa-2x'
          text: ''
          link: ''
          name: linkedin
        -
          icon: 'fa fa-facebook-square fa-2x'
          text: ''
          link: ''
          name: facebook
        -
          icon: 'fa fa-twitter-square fa-2x'
          text: ''
          link: ''
          name: twitter
        -
          icon: 'fa fa-google-plus-circle fa-2x'
          text: ''
          link: ''
          name: google
        -
          icon: 'fa fa-pinterest-square fa-2x'
          text: ''
          link: ''
          name: pinterest
        -
          icon: 'fa fa-youtube-play fa-2x'
          text: ''
          link: ''
          name: youtube
    block:
      class: 'nomarginleft nomarginright'
  skills-8030:
    attributes:
      stats:
        -
          icon: 'fa fa-flag fa-2x'
          label: 'Years Experience'
          value: '7'
          name: Experience
        -
          icon: 'fa fa-thumbs-up fa-2x'
          label: 'Volunteer Efforts'
          value: '5'
          name: Volunteer
        -
          icon: 'fa fa-comments fa-2x'
          label: Languages
          value: '3'
          name: Languages
        -
          icon: 'fa fa-trophy fa-2x'
          label: Awards
          value: '13'
          name: Awards
      skills:
        -
          title: LeaderShip
          percent: '75'
          name: LeaderShip
        -
          title: Initiative
          percent: '80'
          name: Initiative
        -
          title: Communication
          percent: '95'
          name: Communication
        -
          title: Enthusiaim
          percent: '80'
          name: Enthusiaim
        -
          title: 'Team Work'
          percent: '100'
          name: 'Team Work'
        -
          title: Creativity
          percent: '90'
          name: Creativity
    block:
      class: 'nomarginleft nomarginright'
  bio-4636:
    title: 'Mini Bio'
    attributes:
      name: 'John Smith'
      subtitle: '"Creative and Professional Designer who loves everything around web design & programming."'
      text: "<p>Dean has earned his place as one of the most sought after real estate agents in Toronto. In 2013, Dean was recognized as the #1 producing agent in Century 21 Downtown. Dean makes the real estate process successful as well as enjoyable for everyone he represents. With years of experience ranging from condominiums; investment properties and luxury homes, Dean's main objective is to ensure that each and every individual he represents will feel as though he is working for them alone. Regardless of how insurmountable or unexpected the task, you will experience an agent who approaches each assignment with experience, honesty, and commitment to detail as he is tenacious in fulfilling the particular needs of his clientele. Always on top of market conditions, \n</p><p>\nDean understands value and assists his clients in obtaining it through their residences and investments. His work and dedication have without question added a new level of standards to the industry. </p>"
      signature: DBahl
  cv-9087:
    title: Resume
    attributes:
      class: accent
      label: 'I am ready for any challenge,'
      title: 'Contact Me!'
      linktxt: 'Hire Me'
      link: '#contact'
      linktxt2: 'Download CV'
      icon: 'fa fa-arrow-down'
      location: 'gantry-media://Mikhail_Johnson_Resume2016[203].pdf'
    block:
      variations: center
  sectiontitle-6211:
    title: 'Recent Readings'
    attributes:
      icon: 'fa fa-coffee fa-2x'
      title: 'Recent Readings'
      label: 'Pride & Joy'
      desc: 'Gain insight into my personality and character by viewing my recent readings from books and articles to blogs and publications.'
    block:
      variations: center
  portfolio-6995:
    title: Projects
    attributes:
      items:
        -
          image: 'gantry-media://savannah/edgar.jpg'
          title: 'The Rave'
          label: 'Edgar Allen Poe'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          icon: ''
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          icon: ''
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          icon: ''
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          icon: ''
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
        -
          image: 'gantry-media://savannah/edgar.jpg'
          icon: ''
          title: 'Selfie Pic'
          label: 'BLACK | STAMP'
          link: ''
          name: 'New item'
  sectiontitle-3112:
    title: 'My Experience'
    attributes:
      icon: 'fa fa-wrench fa-2x'
      title: 'MY EXPERIENCE'
      label: 'Path to Success'
      desc: 'Showcasing relevant work experience is critical in highlighting an individual’s career path and progress.'
    block:
      variations: center
  process-3920:
    attributes:
      items:
        -
          title: Planning
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: Designing
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: Implementing
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
        -
          title: Production
          desc: 'Sectetur adipiscing elit. Donec quis erat sed elit scque iaculis. Nullam nec.'
          image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2015/08/selfie-process-1.png'
          icon: 'fa fa-pagelines'
          name: 'New item'
  quote-4332:
    attributes:
      text: 'I believe that we are who we choose to be. Nobody’s going to come and save you, you’ve got to save yourself. Nobody’s going to give you anything. You’ve got to go out and fight for it. Nobody knows what you want except for you. And nobody will be as sorry as you if you don’t get it. So don’t give up on your dreams.'
  sectiontitle-8813:
    title: 'MY Education'
    attributes:
      icon: 'fa fa-trophy fa-2x'
      title: 'MY Education'
      label: 'Power of Learning'
    block:
      variations: center
  timeline-4855:
    attributes:
      sections:
        -
          title: latest
          icon: 'fa fa-graduation-cap'
          name: Education
      items:
        -
          section: latest
          icon: 'fa fa-compass'
          title: 'Mcmaster University'
          link: /
          label: 'Bachelor of Arts'
          desc: 'Hamilton, Ontario'
          date: '1999 - 2003'
          name: 'New item'
        -
          section: latest
          icon: 'fa fa-compass3'
          title: 'Lion Trade Corporation'
          link: /
          label: 'Sleeping Hours'
          desc: 'Hamilton, Ontario'
          date: '2016'
          name: 'New item'
        -
          section: latest
          icon: 'fa fa-compass'
          title: 'Lion Trade Corporation2'
          link: /
          label: 'Awards & Accolades'
          desc: 'Hamilton, Ontario'
          date: '2019'
          name: 'New item'
  sectiontitle-2967:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-bullhorn fa-2x'
      title: 'My Testimonials'
    block:
      variations: center
  owlcarousel-7166:
    title: 'Owl Carousel'
    attributes:
      variant: o3
      nav: disable
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      items:
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - John Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - Jack Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - Jane Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
    block:
      class: 'nomargintop nopaddingtop'
  sectiontitle-4237:
    title: 'Section Title'
    attributes:
      icon: 'fa fa-compress fa-2x'
      title: 'STAY IN TOUCH'
      label: 'Available & Always'
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut lobortis nulla luctus et ultrices posuere cubilia,\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae"
    block:
      variations: center
  selfie-circle-widget-9207:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-phone'
      label: '+1 323-444-4553'
      desc: 'REACH ME ANYTIME'
  selfie-circle-widget-1947:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-paperclip fa-2x'
      label: example@site.com
      desc: 'MY PERSONAL EMAIL'
  selfie-circle-widget-7655:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-twitter'
      label: '@johnsmith'
      desc: 'SEND TWEET'
  selfie-circle-widget-2478:
    title: 'Circle Widget'
    attributes:
      icon: 'fa fa-envelope'
      label: www.johnsmith.com
      desc: 'PROFESSIONAL WEBSITE'
  googlemap-4972:
    title: 'Google Map'
    attributes:
      apikey: AIzaSyBMkRoN_9gBXocQZ-FfBGwLEJayFq7dlXc
      width: 100%
      height: 300px
      maptype: ROADMAP
      latitude: '52.052312'
      longitude: '4.447141'
      zoom: '14'
      defaultmarker: show
      markertext: ''
      markerstate: '1'
      scrollwheel: '0'
      dragging: enabled
      snazzymaps: '[{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}]'
      css:
        class: map-canvas
      extra: {  }
  custom-5682:
    title: 'Contact SC'
    attributes:
      html: '[contact-form-7 id="811" title="Selfie Form"]'
      filter: '1'
  totop-8670:
    title: 'To Top'
    attributes:
      icon: 'fa fa-angle-up fa-fw fa-2x'
      content: ''
    block:
      class: g-flushed
  email-1270:
    attributes:
      email: example@site.com
    block:
      class: 'item_left selfie-footer-email'
  copyright-1736:
    attributes:
      date:
        start: '2016'
        end: now
      owner: 'ProfTeam All Rights Reserved.'
      link: 'http://www.profteamsolutions.com'
      target: _blank
      additional:
        text: ''
    block:
      class: selfie-copyrights
  phone-9918:
    attributes:
      tel: +1323-444-4553
    block:
      class: 'selfie-footer-phone item_right'
