version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home
  timestamp: 1472319055
layout:
  /navigation/:
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
      - 'social-3171 20'
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 'infocard-6612 33.3'
      - 'infocard-4698 33.3'
      - 'infocard-5797 33.3'
  /features/:
    -
      - sectiontitle-7684
    -
      - 'profile-6383 33.3'
      - 'bio-info-7430 33.3'
      - 'bio-4636 33.3'
  /resume/:
    -
      - cv-9087
  /protfolio/:
    -
      - sectiontitle-6211
    -
      - portfolio-6995
  /utility/:
    -
      - sectiontitle-3112
    -
      - process-3920
  /above/:
    -
      - sectiontitle-8813
    -
      - timeline-4855
  /testimonials/:
    -
      - sectiontitle-2967
    -
      - owlcarousel-7166
  /expanded/:
    -
      - custom-6355
  /container-main/:
    -
      -
        'mainbar 90':
          -
            - sectiontitle-4237
          -
            - custom-2771
          -
            - custom-5682
      -
        'sidebar 10': {  }
  /footer/:
    -
      - totop-8670
    -
      - 'custom-1125 25'
      - 'copyright-1736 50'
      - 'custom-9450 25'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  resume:
    type: section
    attributes:
      boxed: ''
  protfolio:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
  social-3171:
    block:
      class: g-social-header
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      items:
        -
          image: 'gantry-media://header/img01.jpg'
          title: 'Selfie is here!'
          desc: 'Begin your journey with a brand new &raquo;free&laquo; Gantry 5 template from RocketTheme.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonicon: 'fa fa-rocket'
          buttonclass: button-outline
          name: 'Item 1'
        -
          image: 'gantry-media://header/img02.jpg'
          title: 'Selfie is Gantry powered!'
          desc: 'Selfie is based on the powerful Gantry framework.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonclass: button-outline
          name: 'Item 2'
  infocard-6612:
    title: 'Intro Cards'
    attributes:
      title: 'SEO OPTIMIZATION'
      desc: 'Lorem ipsum dolor sit amet, consectetur uos adipisicing elit Expedita voluptatu necessitatibus deleniti nisi.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_notice.png'
  infocard-4698:
    title: 'Intro Cards'
    attributes:
      title: 'CREATIVE DESIGNER'
      desc: 'Lorem ipsum dolor sit amet, consectetur uos adipisicing elit Expedita voluptatu necessitatibus deleniti nisi.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_bulb.png'
  infocard-5797:
    title: 'Intro Cards'
    attributes:
      title: '2015 DESIGN AWARD'
      desc: 'Lorem ipsum dolor sit amet, consectetur uos adipisicing elit Expedita voluptatu necessitatibus deleniti nisi.'
      display: img
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_award.png'
  sectiontitle-7684:
    title: 'Section Title'
    attributes:
      title: 'Myself & More'
      label: 'KNOW ABOUT ME'
      icon: 'fa fa-heart-o fa-2x'
  profile-6383:
    title: 'Profile Image'
    attributes:
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/11/man.jpg'
      title: 'Designer / Photographer'
      desc: 'Hey, I''m a Creative Photographer and Designer from the United States, NY. I hold a master degree in Computer Design from NY University molestias fuga doloremin.'
  bio-info-7430:
    title: 'Bio Info'
    attributes:
      dob: '1988-06-15'
      phone: 416-123-4567
      email: selfie@msn.ca
      web: 'http://www.example.com'
      address: '12 Segun Bagicha, 10th Floor, Melbourne21118 Australia'
      social: '1'
      target: _blank
      display: both
      skills:
        -
          title: PHP
          percent: '75'
          name: 'New item'
        -
          title: java
          percent: '67'
          name: 'New item'
        -
          title: 'html / css'
          percent: '80'
          name: 'New item'
        -
          title: wordpress
          percent: '95'
          name: 'New item'
  bio-4636:
    title: 'Mini Bio'
    attributes:
      name: 'John Smith'
      subtitle: 'Creative and Professional Designer who loves everything around web design & programming.'
      text: "<p>Placeat dolorum expedita modi corporis molestias fuga fugaingas consectetur pariatur dolorem neque deserunt.</p>\n<p>Placeat dolorum expedita modi corporis molestias fuga doloremin consectetur pariatur dolorem.</p>"
      image: 'http://themes.profteamsolutions.com/selfie/wp-content/uploads/2014/09/selfie_signature_new.png'
  cv-9087:
    title: Resume
    attributes:
      label: 'I am ready for any Project,'
      title: 'Contact Me?'
      linktxt: 'Hire Me'
      link: '#contact'
      linktxt2: 'Download CV'
      icon: 'fa fa-arrow-down'
      location: 'gantry-media://Mikhail_Johnson_Resume2016[203].pdf'
  sectiontitle-6211:
    title: 'Section Title'
    attributes:
      title: 'LATEST PROJECTS'
      label: 'Pride & Joy'
      icon: 'fa fa-coffee fa-2x'
  sectiontitle-3112:
    title: 'Section Title'
    attributes:
      title: 'MY PROCESS'
      icon: 'fa fa-wrench fa-2x'
  sectiontitle-8813:
    title: 'Section Title'
    attributes:
      title: 'MY EXPERIENCE'
      label: 'Wide & Powerful'
      icon: 'fa fa-trophy fa-2x'
  sectiontitle-2967:
    title: 'Section Title'
    attributes:
      title: 'My References'
      icon: 'fa fa-bullhorn fa-2x'
  owlcarousel-7166:
    title: 'Owl Carousel'
    attributes:
      dots: enable
      autoplay: enable
      imageOverlay: disable
      items:
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - John Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - Jack Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: ''
          desc: '"Lorem ipsum dolor sit amet, consectetur adipisicing elit Expedita voluptatum necessitatibus deleniti nisi. Loremu ips umdolorio amet, consectetur." - Jane Doe'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
  custom-6355:
    title: 'Develop CMS themes quickly'
    attributes:
      html: "<div class=\"fp-multi-column-text\">\n    <h2 class=\"g-title\">Develop CMS themes quickly and efficiently</h2>\n    <div class=\"g-grid\">\n        <div class=\"g-block size-50\">\n            <p>\n                Selfie was crafted with love by the <a href=\"http://rockettheme.com\">RocketTheme</a> team to showcase the capabilities of the Gantry 5 framework. Selfie is open source and available for free under a dual license system (<a href=\"http://www.opensource.org/licenses/mit-license.php\">MIT</a> or <a href=\"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html\">GPL version 2 or later</a>). You do not have to keep the Gantry or RocketTheme links and logos in the front end, however, you must ensure that all copyright notices in the code are retained.\n            </p>\n        </div>\n        <div class=\"g-block size-50\">\n            <p>\n                Documentation for Gantry 5 is available on the <a href=\"http://docs.gantry.org\">official Gantry website</a>. You can submit any issues or feature requests for Gantry through <a href=\"http://github.com/gantry/gantry5\">GitHub</a>. A chat room has been set up using <a href=\"https://gitter.im/gantry/gantry5\">Gitter</a> where you can go to talk about the project with developers, contributors, and other members of the community. This is the best place to go to get quick tips and discuss features with others.\n            </p>\n        </div>\n    </div>\n</div>"
    block:
      variations: title-center
  sectiontitle-4237:
    title: 'Section Title'
  custom-2771:
    title: 'Custom HTML'
  custom-5682:
    title: 'Custom HTML'
  totop-8670:
    title: 'To Top'
    attributes:
      icon: 'fa fa-chevron-up fa-fw'
      content: ''
  custom-1125:
    title: 'Custom HTML'
    attributes:
      html: '<a href="mailto:example@site.com">example@site.com</a>'
    block:
      class: selfie-footer-email
  copyright-1736:
    attributes:
      date:
        start: '2016'
        end: now
      owner: ProfTeam
      link: 'http://www.profteamsolutions.com'
      target: _blank
      additional:
        text: 'All Rights Reserved.'
  custom-9450:
    title: 'Custom HTML'
    attributes:
      html: '<a href="tel:+1323-444-4553">+1323-444-4553</a>'
    block:
      class: selfie-footer-phone
